export default [
  {
    productType: "Ботильоны",
    brandName: "Trewww",
    imgUrl: "images/products/1.webp",
    price: "15 000 тг.",
    sold: true,
    inCart: false,
  },
  {
    productType: "Ботильоны",
    brandName: "Calvin Clein",
    imgUrl: "images/products/3.jpg",
    price: "6 000 тг.",
    sold: false,
    inCart: true,
  },
  {
    productType: "Ботильоны",
    brandName: "Yoourrw",
    imgUrl: "images/products/10.webp",
    price: "106 000 тг.",
    sold: true,
    inCart: false,
  },
  {
    productType: "Ботильоны",
    brandName: "Lopppe",
    imgUrl: "images/products/5.webp",
    price: "15 000 тг.",
    sold: false,
    inCart: false,
  },
  {
    productType: "Ботильоны",
    brandName: "Trewww",
    imgUrl: "images/products/10.webp",
    price: "15 000 тг.",
    sold: false,
    inCart: false,
  },
  {
    productType: "Ботильоны",
    brandName: "Calvin Clein",
    imgUrl: "images/products/9.webp",
    price: "6 000 тг.",
    sold: false,
    inCart: false,
  },
  {
    productType: "Ботильоны",
    brandName: "Yoourrw",
    imgUrl: "images/products/2.webp",
    price: "106 000 тг.",
    sold: false,
    inCart: true,
  },
  {
    productType: "Ботильоны",
    brandName: "Lopppe",
    imgUrl: "images/products/6.jpg",
    price: "15 000 тг.",
    sold: true,
    inCart: false,
  },
];
